import React from 'react';
import { useNavigate } from 'react-router-dom';

const Splash = () => {
    const navigate = useNavigate();

    const handleGetStarted = () => {
        navigate('/qr-login');
    };

    return (
        <div className="splash-container">
            <div className="splash-hero">
                <div className="hero-content">
                    <h1 className="hero-title">
                        Welcome to <span className="brand">CodeGame.ai</span>
                    </h1>
                    <p className="hero-subtitle">
                        Transform any QR code into an AI-powered puzzle challenge
                    </p>
                    <p className="hero-description">
                        Scan QR codes with your mobile device, solve unique puzzles generated by AI,
                        and earn Code Points. Track your progress on this web dashboard.
                    </p>
                </div>

                <div className="hero-features">
                    <div className="feature">
                        <div className="feature-icon">📱</div>
                        <h3>Mobile Scanning</h3>
                        <p>Use your phone to scan any QR code - restaurant menus, product labels, websites, anything!</p>
                    </div>

                    <div className="feature">
                        <div className="feature-icon">🧩</div>
                        <h3>AI-Generated Puzzles</h3>
                        <p>Our AI creates unique puzzle challenges based on your QR scan data and location.</p>
                    </div>

                    <div className="feature">
                        <div className="feature-icon">🏆</div>
                        <h3>Earn Code Points</h3>
                        <p>Complete puzzles to earn points, climb leaderboards, and track your progress.</p>
                    </div>
                </div>
            </div>

            <div className="splash-cta">
                <h2>Ready to Start Your Puzzle Journey?</h2>
                <p>Get started by linking your mobile device to this dashboard</p>

                <button
                    className="cta-button"
                    onClick={handleGetStarted}
                >
                    Link Mobile Device
                </button>

                <div className="how-it-works">
                    <h3>How It Works:</h3>
                    <ol>
                        <li>Click "Link Mobile Device" to generate a QR code</li>
                        <li>Scan the QR code with your mobile device</li>
                        <li>Start scanning QR codes in the real world</li>
                        <li>Solve AI-generated puzzles and earn points</li>
                        <li>Track your progress on this dashboard</li>
                    </ol>
                </div>
            </div>

            <div className="splash-footer">
                <p>
                    <strong>CodeGame.ai</strong> - Where every QR code becomes an adventure
                </p>
            </div>
        </div>
    );
};

export default Splash; 